config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Tasks', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    
    /**
     * Allow .json data views everywhere
     */
    $routes->setExtensions(['json']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Task.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Task Entity
 *
 * @property int $id
 * @property int $category_id
 * @property datetime $completed
 * @property string $name
 * @property string|null $description
 * @property int|null $priority
 * @property \Cake\I18n\FrozenTime|null $created
 * @property \Cake\I18n\FrozenTime|null $modified
 *
 * @property \App\Model\Entity\Category $category
 * @property \App\Model\Entity\Tag[] $tags
 */
class Task extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'category_id' => true,
        'name' => true,
        'completed' => true,
        'description' => true,
        'priority' => true,
        'created' => true,
        'modified' => true,
        'category' => true,
        'tags' => true,
    ];
    
    /**
     * Get formatted version of completed field
     * 
     * @return string
     */
    protected function _getCompletedFormat()
    {
        $completed = $this->_properties['completed'];
        
        if ($completed)
        {
            return $completed;
        }
        return '<i>No</i>';
    }

}

src/Model/Table/TasksTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;
use Cake\Event\Event;
use ArrayObject;

/**
 * Tasks Model
 *
 * @property \App\Model\Table\CategoriesTable&\Cake\ORM\Association\BelongsTo $Categories
 * @property \App\Model\Table\TagsTable&\Cake\ORM\Association\BelongsToMany $Tags
 *
 * @method \App\Model\Entity\Task get($primaryKey, $options = [])
 * @method \App\Model\Entity\Task newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Task[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Task|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Task saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Task patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Task[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Task findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class TasksTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('tasks');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
        $this->addBehavior('NullifyText', ['fields' => [
                'description'
        ]]);

        $this->belongsTo('Categories');
        $this->belongsToMany('Tags');
        $this->hasMany('TagsTasks')
                ->setDependent(true); // Enable cascading delete
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
                ->integer('id')
                ->allowEmptyString('id', null, 'create');

        $validator
                ->scalar('category_id')
                ->requirePresence('category_id', 'create');

        $validator
                ->scalar('name')
                ->maxLength('name', 200)
                ->requirePresence('name', 'create')
                ->notEmptyString('name');

        $validator
                ->scalar('completed')
                ->dateTime('completed');

        $validator
                ->scalar('description')
                ->allowEmptyString('description');

        $validator
                ->nonNegativeInteger('priority')
                ->allowEmptyString('priority');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['category_id'], 'Categories'));

        return $rules;
    }

    /**
     * Finder for all uncompleted tasks
     * 
     * @param Query $query
     * @param array $options
     */
    public function findOpen(Query $query, array $options)
    {
        return $query->where('Tasks.completed IS NULL')
                        ->order(['Tasks.priority' => 'desc']);
    }

    /**
     * Finder for all tasks based on filter fom
     * 
     * @param Query $query
     * @param array $options
     */
    public function findFilter(Query $query, array $options)
    {
        if (!isset($options['filter']) || !$options['filter'])
        {
            return $query;
        }
        
        $filter = $options['filter'];
        
        if (isset($filter['priority']) && $filter['priority'])
        {
            $query->where(['Tasks.priority' => $filter['priority']]);
        }
        
        if (isset($filter['tag_id']) && $filter['tag_id'])
        {
            $query->matching('Tags', function ($q) use ($filter) {
                return $q->where(['Tags.id' => $filter['tag_id']]);
            });
        }
        
        return $query;
    }

    /**
     * Finder for all completed tasks
     * 
     * @param Query $query
     * @param array $options
     */
    public function findArchive(Query $query, array $options)
    {
        return $query
                        ->select($this)
                        ->select(['category_name' => 'Categories.name'])
                        ->where('Tasks.completed IS NOT NULL')
                        ->innerJoinWith('Categories', function ($q) {
                            return $q->find('all', ['archive' => true]);
                        });
    }

}

src/Controller/TasksController.php
<?php

namespace App\Controller;

use App\Controller\AppController;
use Cake\Http\Exception\BadRequestException;
use Cake\I18n\FrozenTime;

/**
 * Tasks Controller
 *
 * @property \App\Model\Table\TasksTable $Tasks
 *
 * @method \App\Model\Entity\Task[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class TasksController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
        $categories = $this->Tasks->Categories->find('open', ['filter' => $this->request->getQuery()])
                ->contain('Tasks.Tags');

        $tags_list = $this->Tasks->Tags->find('list', ['limit' => 200]);
        
        $this->set(compact('categories', 'tags_list'));
    }

    /**
     * Archive page with all completed tasks
     */
    public function indexArchive()
    {
        $this->paginate = [
            'limit' => 20,
            'order' => [
                'Tasks.completed' => 'desc'
            ],
            'sortWhitelist' => ['Tasks.name', 'Tasks.completed', 'Categories.name', 'Tasks.priority']
        ];

        $tasks = $this->Tasks->find('archive');

        $this->set('tasks', $this->paginate($tasks));
    }

    /**
     * View method
     *
     * @param string|null $id Task id
     */
    public function view($id = null)
    {
        $task = $this->Tasks->get($id, [
            'contain' => ['Categories'],
        ]);

        $this->set(compact('task'));
    }

    /**
     * Combined add and edit method
     *
     * @param string|null $id Task id
     */
    public function edit($id = null)
    {
        if ($id)
        {
            $task = $this->Tasks->get($id);
        }
        else
        {
            $task = $this->Tasks->newEntity();
        }

        if ($this->request->is(['patch', 'post', 'put']))
        {
            $this->Tasks->patchEntity($task, $this->request->getData());

            if ($this->Tasks->save($task))
            {
                $this->Flash->success('The task has been saved');

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error('The task could not be saved, please try again');
        }

        $categories = $this->Tasks->Categories->find('list', ['limit' => 200]);
        $tags = $this->Tasks->Tags->find('list', ['limit' => 200]);
        $this->set(compact('task', 'categories', 'tags'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Task id
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);

        $task = $this->Tasks->get($id);

        if ($this->Tasks->delete($task))
        {
            $this->Flash->success('The task has been deleted');
        }
        else
        {
            $this->Flash->error('The task could not be deleted. Please, try again.');
        }

        return $this->redirect(['action' => 'index']);
    }

    /**
     * Search for tasks (JSON page)
     * 
     * Use 'term' query parameters for search query
     */
    public function search()
    {
        $q = $this->request->getQuery('term', false);

        if (!$q)
        {
            throw new BadRequestException('Missing the `term` search query');
        }

        $tasks = $this->Tasks->find()
                ->select(['id' => 'id', 'label' => 'name', 'value' => 'name'])
                ->where('completed IS NULL')
                ->where(['OR' => [
                        ['name LIKE' => "%{$q}%"],
                        ['description LIKE' => "%{$q}%"]
            ]])
                ->disableHydration();

        $this->set(compact('tasks'));
    }

    /**
     * Complete a task
     * 
     * @param int|string $id Task id
     */
    public function complete($id = null)
    {
        $this->request->allowMethod(['post', 'patch']);

        $task = $this->Tasks->get($id);

        $task->completed = new FrozenTime();

        if ($this->Tasks->save($task))
        {
            $this->Flash->success('Completed task!');
        }
        else
        {
            $this->Flash->error('Failed to complete task...');
        }

        return $this->redirect('/');
    }

}

src/Template/Tasks/edit.ctp
<h1>
    <?= $task->isNew() ? 'Create new task' : 'Edit task' ?>
</h1>

<?php
$sources = ['context'];

if ($task->isNew())
{
    $sources[] = 'query';
}
?>
<?= $this->Form->create($task, ['valueSources' => $sources]) ?>
<?= $this->Form->control('name') ?>
<?= $this->Form->control('category_id') ?>
<?= $this->Form->control('tags._ids') ?>
<?= $this->Form->control('description', ['type' => 'textarea', 'rows' => 1]) ?>
<?=
$this->Form->control('priority', [
    'type' => 'select',
    'options' => [0 => 'Low', 1 => 'Medium', 2 => 'High', 3 => 'Critical']
])
?>
<?= $this->Form->submit('Save') ?>
<?= $this->Form->end() ?>

<div class="button-panel">
    <?= $this->Html->link('Cancel', '/', ['class' => 'btn btn-outline-secondary']) ?>

    <?php
    if (!$task->isNew())
    {
        echo $this->Form->postLink(
                '<i class="fas fa-trash"></i>&nbsp;Delete',
                ['action' => 'delete', $task->id],
                ['class' => 'btn btn-outline-danger', 'escape' => false, 'confirm' => 'Delete this task?']);
    }
    ?>
</div>

src/Template/Tasks/index.ctp
<?php
$this->assign('current_menu', 'Tasks');

$collapse = '';
if ($this->request->getQuery())
{
    $collapse = ' show';
}
?>

<h1>Open Tasks</h1>

<button class="btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#filter-panel" aria-expanded="false" aria-controls="filter-panel">
    Filters >
</button>
<div class="collapse<?= $collapse ?>" id="filter-panel">
    <div class="card card-body">
        <?= $this->Form->create(null, ['type' => 'GET', 'valueSources' => ['query']]) ?>
        <?=
        $this->Form->control('priority', [
            'type' => 'select',
            'options' => [0 => 'Low', 1 => 'Medium', 2 => 'High', 3 => 'Critical'],
            'empty' => 'All'
        ])
        ?>
        <?=
        $this->Form->control('tag_id', [
            'type' => 'select',
            'options' => $tags_list,
            'empty' => 'All'
        ])
        ?>
        <?= $this->Form->submit('Search') ?>
        <?= $this->Form->end() ?>
    </div>
</div>
<br><br>

<div class="card-deck categories-deck">
    <?php foreach ($categories as $category) : ?>
        <?= $this->element('Categories/card', compact('category')) ?>
    <?php endforeach; ?>
</div>

<div class="button-panel">
    <?=
    $this->Html->link(
            '<i class="fas fa-plus"></i>&nbsp;New Category',
            ['controller' => 'Categories', 'action' => 'edit'],
            ['class' => 'btn btn-outline-info', 'escape' => false])
    ?>
</div>

src/Template/Tasks/index_archive.ctp
<?php
$this->assign('current_menu', 'Archive');
?>

<h1>Completed Tasks</h1>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th><?= $this->Paginator->sort('Tasks.name', 'Name') ?></th>
                <th><?= $this->Paginator->sort('Tasks.completed', 'Completed') ?></th>
                <th><?= $this->Paginator->sort('Tasks.priority', 'Priority') ?></th>
                <th><?= $this->Paginator->sort('Categories.name', 'Category') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tasks as $task): ?>
            <tr>
                <td><?= h($task->name) ?></td>
                <td><?= h($task->completed_format) ?></td>
                <td>P<?= $task->priority ?></td>
                <td><?= h($task->category_name) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?= $this->element('pagination_panel') ?>

src/Template/Tasks/view.ctp
<h1>View Task</h1>

<?=
$this->Html->link(
        'Back',
        ['action' => 'index'],
        ['class' => 'btn btn-secondary'])
?>

<br><br>

<table class="table vertical-table">
    <tbody>
        <tr>
            <th>Name</th>
            <td><?= $task->name ?></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?= $task->description ?></td>
        </tr>
        <tr>
            <th>Category</th>
            <td><?= $task->category->name ?></td>
        </tr>
        <tr>
            <th>Completed</th>
            <td><?= $task->completed_format ?></td>
        </tr>
    </tbody>
</table>

<div class="button-panel">
    <?=
    $this->Html->link(
            '<i class="fas fa-edit"></i>&nbsp;Edit',
            ['action' => 'edit', $task->id],
            ['class' => 'btn btn-outline-info', 'escape' => false])
    ?>
</div>